// Code generated by brandkit.py. DO NOT EDIT.

package main

import "github.com/charmbracelet/lipgloss"

// Brand colors resolved per color profile. CompleteColor disables
// lipgloss's automatic degradation, so each tier is chosen
// deliberately rather than derived by nearest-neighbour at runtime.
var brand = struct {
	Accent lipgloss.CompleteAdaptiveColor
	Ok     lipgloss.CompleteAdaptiveColor
	Err    lipgloss.CompleteAdaptiveColor
}{
	Accent: lipgloss.CompleteAdaptiveColor{
		Dark:  lipgloss.CompleteColor{TrueColor: "#956cee", ANSI256: "99", ANSI: "12"},
		Light: lipgloss.CompleteColor{TrueColor: "#6f42c1", ANSI256: "62", ANSI: "4"},
	},
	Ok: lipgloss.CompleteAdaptiveColor{
		Dark:  lipgloss.CompleteColor{TrueColor: "#2f9662", ANSI256: "29", ANSI: "2"},
		Light: lipgloss.CompleteColor{TrueColor: "#198754", ANSI256: "29", ANSI: "2"},
	},
	Err: lipgloss.CompleteAdaptiveColor{
		Dark:  lipgloss.CompleteColor{TrueColor: "#ee4853", ANSI256: "167", ANSI: "9"},
		Light: lipgloss.CompleteColor{TrueColor: "#dc3545", ANSI256: "160", ANSI: "1"},
	},
}
