.PHONY: build test fmt check fmt-check vet palette-check demo clean

build: ## Compile the binary
	go build -o bin/mkui .

test: ## Run the test suite
	go test ./...

check: fmt-check vet palette-check test ## Everything CI runs; the gate before "done"

fmt-check: ## Fail if anything is unformatted
	@out=$$(gofmt -l .); test -z "$$out" || { echo "unformatted:"; echo "$$out"; exit 1; }

vet: ## go vet
	go vet ./...

palette-check: ## Fail if a theme-blind color literal reaches the base UI
	@if grep -nE '"(1[6-9]|[1-9][0-9]{2}|[2-9][0-9])"|"#[0-9a-fA-F]{3,8}"' ui.go theme.go; then \
		echo ""; \
		echo "ERROR: colors 16-255 and hex are theme-blind and break on light backgrounds."; \
		echo "The base theme must use ANSI 0-15 only. Brand colors belong in brand.go,"; \
		echo "generated by tools/brandkit.py with contrast repair."; \
		exit 1; \
	fi

fmt: ## Format all Go source
	gofmt -w .

demo: build ## Regenerate the demo GIF and theme frames
	vhs demo/demo.tape && vhs demo/themes.tape

clean: ## Remove build artifacts
	rm -rf bin dist demo/frames demo/*.gif
