package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

// writeFixture drops each named file into a fresh temp dir and returns the dir.
// Fixtures are whole makefiles (plus any includes) so the tests exercise the
// same make invocation the real program does.
func writeFixture(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for name, body := range files {
		p := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

func names(targets []Target) map[string]bool {
	m := make(map[string]bool, len(targets))
	for _, tg := range targets {
		m[tg.Name] = true
	}
	return m
}

func requireMake(t *testing.T) {
	t.Helper()
	if _, err := exec.LookPath("make"); err != nil {
		t.Skip("make not on PATH")
	}
}

// TestLoadTargets covers the cases only make's own rule database can get right:
// includes, $(shell)-generated targets, and the exclusions. Each case is a
// whole fixture makefile run through the real make.
func TestLoadTargets(t *testing.T) {
	requireMake(t)

	for _, tc := range []struct {
		name   string
		files  map[string]string
		want   []string // must be offered as targets
		absent []string // must not be offered
	}{
		{
			name: "target from an included file appears",
			files: map[string]string{
				"Makefile":    "include included.mk\n",
				"included.mk": "included-target:\n\t@echo inc\n",
			},
			want: []string{"included-target"},
			// the included makefile is itself a file make tracks, but not a target
			absent: []string{"included.mk"},
		},
		{
			name: "target generated by $(shell ...) appears",
			files: map[string]string{
				"Makefile": "GEN := $(shell echo generated-target)\n" +
					"$(GEN):\n\t@echo gen\n",
			},
			want: []string{"generated-target"},
		},
		{
			name: "pattern rules, .PHONY and the makefile itself are excluded",
			files: map[string]string{
				"Makefile": ".PHONY: build\n" +
					"build:\n\t@echo build\n" +
					"%.o:\n\t@echo pattern\n" +
					"concrete.o:\n\t@echo concrete\n",
			},
			want:   []string{"build", "concrete.o"},
			absent: []string{"%.o", ".PHONY", ".SUFFIXES", ".DEFAULT", "Makefile"},
		},
		{
			// Double-colon rules are legal make; each `::` entry is independent.
			// make emits them as `archive::`, so the name filter must accept the
			// second colon or the target vanishes from the list. The plain
			// `build:` target keeps the database parse non-empty, so a name-filter
			// regression cannot hide behind the file-scan fallback (which has its
			// own `::?` and would otherwise mask it).
			name: "double-colon rules are offered",
			files: map[string]string{
				"Makefile": "build:\n\t@echo b\n" +
					"archive:: ## first half\n\t@echo one\n" +
					"archive:: ## second half\n\t@echo two\n",
			},
			want: []string{"build", "archive"},
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			dir := writeFixture(t, tc.files)
			targets, err := LoadTargets(dir, "Makefile")
			if err != nil {
				t.Fatal(err)
			}
			got := names(targets)
			for _, n := range tc.want {
				if !got[n] {
					t.Errorf("target %q missing; got %v", n, got)
				}
			}
			for _, n := range tc.absent {
				if got[n] {
					t.Errorf("target %q should be excluded; got %v", n, got)
				}
			}
		})
	}
}

// TestLoadTargetsIncludedTargetKeepsDoc covers the regression where a target
// pulled in from an `include`d makefile appeared in the list but lost its `##`
// description, because docs were only read from the top-level file. The set of
// makefiles to scan is taken from make's own database, including a subdir path.
func TestLoadTargetsIncludedTargetKeepsDoc(t *testing.T) {
	requireMake(t)

	dir := writeFixture(t, map[string]string{
		"Makefile": "include common.mk\n" +
			"include sub/extra.mk\n" +
			"build: ## Compile the binary\n\t@echo build\n",
		"common.mk":    "deploy: ## Ship it to prod\n\t@echo deploy\n",
		"sub/extra.mk": "lint: ## Static checks\n\t@echo lint\n",
	})

	targets, err := LoadTargets(dir, "Makefile")
	if err != nil {
		t.Fatal(err)
	}
	got := map[string]string{}
	for _, tg := range targets {
		got[tg.Name] = tg.Doc
	}
	for name, want := range map[string]string{
		"build":  "Compile the binary", // top-level
		"deploy": "Ship it to prod",    // from common.mk
		"lint":   "Static checks",      // from sub/extra.mk
	} {
		if got[name] != want {
			t.Errorf("doc for %q = %q, want %q", name, got[name], want)
		}
	}
}

// TestParseDatabaseNotATargetDoesNotSwallowNextTarget guards invariant #5: a
// "# Not a target:" marker must be cleared by the *next* rule-shaped line even
// when the name filter rejects that line (.DEFAULT here). An earlier version
// cleared the flag only on accepted lines, so the skip leaked past .DEFAULT and
// silently ate `real-target`. Real make never emits this exact adjacency in any
// ordering, so it is asserted against a fixed database rather than a fixture.
func TestParseDatabaseNotATargetDoesNotSwallowNextTarget(t *testing.T) {
	db := []byte("# Files\n" +
		"\n" +
		"# Not a target:\n" +
		".DEFAULT:\n" +
		"#  a make comment about .DEFAULT\n" +
		"\trecipe\n" +
		"\n" +
		"real-target:\n" +
		"\trecipe\n" +
		"\n" +
		"# files hash-table stats:\n")

	targets, err := parseDatabase(db)
	if err != nil {
		t.Fatal(err)
	}
	got := names(targets)
	if !got["real-target"] {
		t.Fatalf("real-target was swallowed by the .DEFAULT skip; got %v", got)
	}
	if got[".DEFAULT"] {
		t.Errorf(".DEFAULT is not a runnable target and must not be offered; got %v", got)
	}
}

// TestLoadTargetsFallsBackWhenMakeAbsent covers the plain-file scan used when
// make cannot be run. It sees ordinary targets but, by design, misses anything
// that only exists after make evaluates the makefile — the very gap the
// database path closes.
func TestLoadTargetsFallsBackWhenMakeAbsent(t *testing.T) {
	dir := writeFixture(t, map[string]string{
		"Makefile":    "include included.mk\nlocal-target:\n\t@echo local\n",
		"included.mk": "included-target:\n\t@echo inc\n",
	})

	t.Setenv("PATH", "") // make is now unresolvable, forcing the file scan

	targets, err := LoadTargets(dir, "Makefile")
	if err != nil {
		t.Fatal(err)
	}
	got := names(targets)
	if !got["local-target"] {
		t.Errorf("file fallback missed a plainly-written target; got %v", got)
	}
	if got["included-target"] {
		t.Errorf("file fallback cannot see includes yet reported one; got %v", got)
	}
}

// TestParseDocs covers `## ` doc extraction, including that prerequisites before
// the comment are ignored, that a `#`-commented line is not mistaken for a
// documented target, and that a `#`/`##` appearing inside a recipe does not
// leak in as a doc — the recipe lines below look exactly like doc lines but are
// tab-indented, and only a start-of-line rule may carry a doc.
func TestParseDocs(t *testing.T) {
	dir := writeFixture(t, map[string]string{
		"Makefile": "build: ## Compile the binary\n" +
			"\t@echo '# a bare hash in the recipe'\n" +
			"\t@echo 'build: ## a fake doc echoed by the recipe'\n" +
			"deploy: dep1 dep2 ## Ship it\n\t@echo d\n" +
			"nodoc:\n\t@echo n\n" +
			"# commented: ## not a real doc\n",
	})

	docs := parseDocs(dir, []string{"Makefile"})

	for name, want := range map[string]string{
		// The real doc, not the "fake doc" the recipe's second line echoes.
		"build":  "Compile the binary",
		"deploy": "Ship it",
	} {
		if docs[name] != want {
			t.Errorf("doc[%q] = %q, want %q", name, docs[name], want)
		}
	}
	if doc, ok := docs["nodoc"]; ok {
		t.Errorf("nodoc has no `##` comment but got doc %q", doc)
	}
	if _, ok := docs["commented"]; ok {
		t.Error("a #-commented line was mistaken for a documented target")
	}
}
