package main

import (
	"bufio"
	"bytes"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// Target is a single runnable make target.
type Target struct {
	Name  string
	Doc   string // text after a `## ` comment on the target line
	Phony bool
}

// GNU make itself tries these names, in this order.
var makefileNames = []string{"GNUmakefile", "makefile", "Makefile"}

// FindMakefile walks up from start until it finds a makefile, so `mkui` works
// from a subdirectory of a repo the same way most other dev tools do.
func FindMakefile(start string) (dir, name string, err error) {
	abs, err := filepath.Abs(start)
	if err != nil {
		return "", "", err
	}
	for {
		for _, n := range makefileNames {
			if st, err := os.Stat(filepath.Join(abs, n)); err == nil && !st.IsDir() {
				return abs, n, nil
			}
		}
		parent := filepath.Dir(abs)
		if parent == abs {
			return "", "", errors.New("no Makefile found here or in any parent directory")
		}
		abs = parent
	}
}

// LoadTargets returns every target make knows about, annotated with `##` docs.
func LoadTargets(dir, name string) ([]Target, error) {
	targets, err := targetsFromDatabase(dir)
	if err != nil || len(targets) == 0 {
		// make is missing or the makefile has an error; degrade to a plain
		// scan of the file. Misses includes and generated targets, but it is
		// better than showing nothing.
		targets = targetsFromFile(filepath.Join(dir, name))
	}

	docs := parseDocs(filepath.Join(dir, name))
	for i := range targets {
		targets[i].Doc = docs[targets[i].Name]
	}

	// Documented targets first (those are the ones authors meant to expose),
	// then everything else, alphabetically within each group.
	sort.SliceStable(targets, func(i, j int) bool {
		di, dj := targets[i].Doc != "", targets[j].Doc != ""
		if di != dj {
			return di
		}
		return targets[i].Name < targets[j].Name
	})
	return targets, nil
}

var (
	// Any line that is shaped like a rule, however it is named. Used only to
	// know that a "# Not a target:" marker has been consumed.
	anyRuleRe = regexp.MustCompile(`^[^\s#].*?::?(\s|$)`)
	// A rule whose target name we are willing to offer to the user. Excludes
	// pattern rules (%.o), special targets (.PHONY) and variable assignments.
	nameRe = regexp.MustCompile(`^([A-Za-z0-9_][A-Za-z0-9_./+-]*)\s*::?(\s|$)`)
)

// targetsFromDatabase asks make to dump its own parsed rule database.
//
// This is the only reliable way to see targets that come from `include`d
// files or are generated by `$(shell ...)`/macros. Flags:
//
//	-p  print the database
//	-R  no built-in variables
//	-r  no built-in implicit rules
//	-q  question mode: never actually run a recipe
//
// Caveat worth knowing: -p still *evaluates* the makefile, so any `$(shell
// ...)` at parse time does execute. That is make's behaviour, not ours, but
// it means mkui is not safe to point at a makefile you do not trust.
func targetsFromDatabase(dir string) ([]Target, error) {
	cmd := exec.Command("make", "-pRrq", "--no-print-directory")
	cmd.Dir = dir
	// -q exits 1 when targets are out of date, which is the normal case here,
	// so the exit code is deliberately ignored; empty output is the real error.
	out, _ := cmd.Output()
	if len(out) == 0 {
		return nil, errors.New("make produced no rule database")
	}

	var (
		targets  []Target
		inFiles  bool
		skipNext bool
		last     = -1
	)

	sc := bufio.NewScanner(bytes.NewReader(out))
	sc.Buffer(make([]byte, 0, 64*1024), 8*1024*1024)
	for sc.Scan() {
		line := sc.Text()

		if strings.HasPrefix(line, "# Files") {
			inFiles = true
			continue
		}
		if strings.HasPrefix(line, "# files hash-table stats") {
			inFiles = false
			continue
		}
		if !inFiles {
			continue
		}

		if line == "# Not a target:" {
			skipNext = true
			continue
		}
		if strings.HasPrefix(line, "#") {
			if last >= 0 && strings.Contains(line, "Phony target") {
				targets[last].Phony = true
			}
			continue
		}
		if !anyRuleRe.MatchString(line) {
			continue
		}

		// Any rule-shaped line clears the marker, even one we go on to reject
		// (.DEFAULT, %.o). Otherwise the skip leaks onto the next real target.
		wasSkipped := skipNext
		skipNext = false
		if wasSkipped {
			continue
		}

		m := nameRe.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		targets = append(targets, Target{Name: m[1]})
		last = len(targets) - 1
	}
	return targets, sc.Err()
}

var fileTargetRe = regexp.MustCompile(`^([A-Za-z0-9_][A-Za-z0-9_./+-]*)\s*::?([^=]|$)`)

// targetsFromFile is the fallback scan used when make is unavailable.
func targetsFromFile(path string) []Target {
	f, err := os.Open(path)
	if err != nil {
		return nil
	}
	defer f.Close()

	seen := map[string]bool{}
	var targets []Target

	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		if strings.HasPrefix(line, "\t") || strings.HasPrefix(line, "#") {
			continue
		}
		m := fileTargetRe.FindStringSubmatch(line)
		if m == nil || seen[m[1]] {
			continue
		}
		seen[m[1]] = true
		targets = append(targets, Target{Name: m[1]})
	}
	return targets
}

// docRe matches the widely used self-documenting convention:
//
//	build: ## Compile the binary
var docRe = regexp.MustCompile(`^([A-Za-z0-9_][A-Za-z0-9_./+-]*)\s*::?[^#]*##\s?(.*)$`)

func parseDocs(path string) map[string]string {
	docs := map[string]string{}
	f, err := os.Open(path)
	if err != nil {
		return docs
	}
	defer f.Close()

	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		if m := docRe.FindStringSubmatch(sc.Text()); m != nil {
			docs[m[1]] = strings.TrimSpace(m[2])
		}
	}
	return docs
}
